// Fight Scene Data - AUTO-GENERATED by scripts/loadFightScenes.cjs
// Run: npm run load-fights

export interface FightScene {
  id: string;
  volumeId: number;
  chapter: string;
  sceneNumber: number;
  title: string;
  characters: string[];
  durationStr: string;
  durationSeconds: number;
  location: string;
  priorityTier: 1 | 2 | 3 | 4;
  promptTemplate: string;
}

export const fightScenes: FightScene[] = [
  {
    id: "fight-v1-Act1-Ch04-s4",
    volumeId: 1,
    chapter: "Act1_Ch04",
    sceneNumber: 4,
    title: "Trial by Combat",
    characters: ["Ren", "Kira", "Monica", "Bradley", "Liora", "Dante", "Solana", "Shadow"],
    durationStr: "12:56",
    durationSeconds: 776,
    location: "Unknown",
    priorityTier: 1 as const,
    promptTemplate: `[SCENE: Trial by Combat]
[VOLUME: 1]
[CHAPTER: Act1_Ch04]
[LOCATION: Unknown]
[CHARACTERS: Ren, Kira, Monica, Bradley, Liora, Dante, Solana, Shadow]
[DURATION: 12:56]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of Unknown
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v3-Act3-Ch06-s4",
    volumeId: 3,
    chapter: "Act3_Ch06",
    sceneNumber: 4,
    title: "The Beast and the Blade",
    characters: ["Ren", "Kira", "Liora", "Fasa", "Shadow"],
    durationStr: "9:20",
    durationSeconds: 560,
    location: "EXT. ARENA FLOOR",
    priorityTier: 1 as const,
    promptTemplate: `[SCENE: The Beast and the Blade]
[VOLUME: 3]
[CHAPTER: Act3_Ch06]
[LOCATION: EXT. ARENA FLOOR]
[CHARACTERS: Ren, Kira, Liora, Fasa, Shadow]
[DURATION: 9:20]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of EXT. ARENA FLOOR
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v2-Act2-Ch08-s8",
    volumeId: 2,
    chapter: "Act2_Ch08",
    sceneNumber: 8,
    title: "Solana Falls",
    characters: ["Ren", "Kira", "Dante", "Solana", "Queen", "Shadow"],
    durationStr: "3:51",
    durationSeconds: 231,
    location: "INT. SHADOW GUILD COURTYARD",
    priorityTier: 1 as const,
    promptTemplate: `[SCENE: Solana Falls]
[VOLUME: 2]
[CHAPTER: Act2_Ch08]
[LOCATION: INT. SHADOW GUILD COURTYARD]
[CHARACTERS: Ren, Kira, Dante, Solana, Queen, Shadow]
[DURATION: 3:51]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of INT. SHADOW GUILD COURTYARD
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v2-Act2-Ch04-s1",
    volumeId: 2,
    chapter: "Act2_Ch04",
    sceneNumber: 1,
    title: "Pre-Dawn Training - Ren's Rhythm",
    characters: ["Ren", "Kira", "Dante", "Solana"],
    durationStr: "8:02",
    durationSeconds: 482,
    location: "INT. GUILD TRAINING ARENA",
    priorityTier: 2 as const,
    promptTemplate: `[SCENE: Pre-Dawn Training - Ren's Rhythm]
[VOLUME: 2]
[CHAPTER: Act2_Ch04]
[LOCATION: INT. GUILD TRAINING ARENA]
[CHARACTERS: Ren, Kira, Dante, Solana]
[DURATION: 8:02]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of INT. GUILD TRAINING ARENA
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v2-Act2-Ch03-s1",
    volumeId: 2,
    chapter: "Act2_Ch03",
    sceneNumber: 1,
    title: "Morning Training with Kira",
    characters: ["Ren", "Kira", "Bradley", "Dante", "Solana", "Shadow"],
    durationStr: "7:08",
    durationSeconds: 428,
    location: "INT. SHADOW GUILD LOWER TRAINI",
    priorityTier: 2 as const,
    promptTemplate: `[SCENE: Morning Training with Kira]
[VOLUME: 2]
[CHAPTER: Act2_Ch03]
[LOCATION: INT. SHADOW GUILD LOWER TRAINI]
[CHARACTERS: Ren, Kira, Bradley, Dante, Solana, Shadow]
[DURATION: 7:08]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of INT. SHADOW GUILD LOWER TRAINI
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v1-Act1-Ch03-s6",
    volumeId: 1,
    chapter: "Act1_Ch03",
    sceneNumber: 6,
    title: "IronFist Meets MetalHead",
    characters: ["Ren", "Monica", "Solana", "Queen", "Shadow"],
    durationStr: "6:13",
    durationSeconds: 373,
    location: "EXT. TRUCK",
    priorityTier: 2 as const,
    promptTemplate: `[SCENE: IronFist Meets MetalHead]
[VOLUME: 1]
[CHAPTER: Act1_Ch03]
[LOCATION: EXT. TRUCK]
[CHARACTERS: Ren, Monica, Solana, Queen, Shadow]
[DURATION: 6:13]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of EXT. TRUCK
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v3-Act3-Ch07-s4",
    volumeId: 3,
    chapter: "Act3_Ch07",
    sceneNumber: 4,
    title: "Two Against Fate",
    characters: ["Ren", "Monica", "Queen"],
    durationStr: "5:58",
    durationSeconds: 358,
    location: "INT. SHRINE CHAMBER",
    priorityTier: 2 as const,
    promptTemplate: `[SCENE: Two Against Fate]
[VOLUME: 3]
[CHAPTER: Act3_Ch07]
[LOCATION: INT. SHRINE CHAMBER]
[CHARACTERS: Ren, Monica, Queen]
[DURATION: 5:58]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of INT. SHRINE CHAMBER
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v2-Act2-Ch03-s8",
    volumeId: 2,
    chapter: "Act2_Ch03",
    sceneNumber: 8,
    title: "Reflection and Meditation",
    characters: ["Ren", "Dante"],
    durationStr: "5:16",
    durationSeconds: 316,
    location: "INT. URBAN DOJO — EVENING**",
    priorityTier: 2 as const,
    promptTemplate: `[SCENE: Reflection and Meditation]
[VOLUME: 2]
[CHAPTER: Act2_Ch03]
[LOCATION: INT. URBAN DOJO — EVENING**]
[CHARACTERS: Ren, Dante]
[DURATION: 5:16]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of INT. URBAN DOJO — EVENING**
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v1-Act1-Ch01-s5",
    volumeId: 1,
    chapter: "Act1_Ch01",
    sceneNumber: 5,
    title: "Street Fight",
    characters: ["Ren", "Monica", "Shadow"],
    durationStr: "4:46",
    durationSeconds: 286,
    location: "EXT. RESTAURANT ALLEY — NIGHT*",
    priorityTier: 3 as const,
    promptTemplate: `[SCENE: Street Fight]
[VOLUME: 1]
[CHAPTER: Act1_Ch01]
[LOCATION: EXT. RESTAURANT ALLEY — NIGHT*]
[CHARACTERS: Ren, Monica, Shadow]
[DURATION: 4:46]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of EXT. RESTAURANT ALLEY — NIGHT*
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v2-Act2-Ch06-s2",
    volumeId: 2,
    chapter: "Act2_Ch06",
    sceneNumber: 2,
    title: "Ridgeline Pass - First Contact",
    characters: ["Ren", "Kira", "Bradley", "Liora", "Solana", "Shadow"],
    durationStr: "4:19",
    durationSeconds: 259,
    location: "EXT. RIDGELINE PASS",
    priorityTier: 3 as const,
    promptTemplate: `[SCENE: Ridgeline Pass - First Contact]
[VOLUME: 2]
[CHAPTER: Act2_Ch06]
[LOCATION: EXT. RIDGELINE PASS]
[CHARACTERS: Ren, Kira, Bradley, Liora, Solana, Shadow]
[DURATION: 4:19]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of EXT. RIDGELINE PASS
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v3-Act3-Ch06-s3",
    volumeId: 3,
    chapter: "Act3_Ch06",
    sceneNumber: 3,
    title: "Liora vs. Kira",
    characters: ["Ren", "Kira", "Monica", "Bradley", "Liora", "Fasa"],
    durationStr: "4:04",
    durationSeconds: 244,
    location: "EXT. RITE OF DOMINION ARENA",
    priorityTier: 3 as const,
    promptTemplate: `[SCENE: Liora vs. Kira]
[VOLUME: 3]
[CHAPTER: Act3_Ch06]
[LOCATION: EXT. RITE OF DOMINION ARENA]
[CHARACTERS: Ren, Kira, Monica, Bradley, Liora, Fasa]
[DURATION: 4:04]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of EXT. RITE OF DOMINION ARENA
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v3-Act3-Ch07-s2",
    volumeId: 3,
    chapter: "Act3_Ch07",
    sceneNumber: 2,
    title: "Squad vs. Scavengers",
    characters: ["Ren", "Kira", "Monica", "Bradley", "Liora", "Queen"],
    durationStr: "3:57",
    durationSeconds: 237,
    location: "INT. SHRINE INTERIOR",
    priorityTier: 3 as const,
    promptTemplate: `[SCENE: Squad vs. Scavengers]
[VOLUME: 3]
[CHAPTER: Act3_Ch07]
[LOCATION: INT. SHRINE INTERIOR]
[CHARACTERS: Ren, Kira, Monica, Bradley, Liora, Queen]
[DURATION: 3:57]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of INT. SHRINE INTERIOR
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v3-Act3-Ch07-s3",
    volumeId: 3,
    chapter: "Act3_Ch07",
    sceneNumber: 3,
    title: "Broken Signal",
    characters: ["Ren", "Kira", "Monica", "Bradley", "Liora", "Queen"],
    durationStr: "3:57",
    durationSeconds: 237,
    location: "INT. SHRINE COMPLEX",
    priorityTier: 3 as const,
    promptTemplate: `[SCENE: Broken Signal]
[VOLUME: 3]
[CHAPTER: Act3_Ch07]
[LOCATION: INT. SHRINE COMPLEX]
[CHARACTERS: Ren, Kira, Monica, Bradley, Liora, Queen]
[DURATION: 3:57]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of INT. SHRINE COMPLEX
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v3-Act3-Ch09-s4",
    volumeId: 3,
    chapter: "Act3_Ch09",
    sceneNumber: 4,
    title: "No More Running (Part 2)",
    characters: ["Ren", "Monica", "Dante"],
    durationStr: "3:41",
    durationSeconds: 221,
    location: "EXT. GLYPH GATE RUINS",
    priorityTier: 3 as const,
    promptTemplate: `[SCENE: No More Running (Part 2)]
[VOLUME: 3]
[CHAPTER: Act3_Ch09]
[LOCATION: EXT. GLYPH GATE RUINS]
[CHARACTERS: Ren, Monica, Dante]
[DURATION: 3:41]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of EXT. GLYPH GATE RUINS
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v2-Act2-Ch06-s4",
    volumeId: 2,
    chapter: "Act2_Ch06",
    sceneNumber: 4,
    title: "Final Ridge - Boss Fight",
    characters: ["Ren", "Kira", "Bradley", "Liora", "Dante", "Shadow"],
    durationStr: "3:24",
    durationSeconds: 204,
    location: "EXT. FINAL RIDGE",
    priorityTier: 3 as const,
    promptTemplate: `[SCENE: Final Ridge - Boss Fight]
[VOLUME: 2]
[CHAPTER: Act2_Ch06]
[LOCATION: EXT. FINAL RIDGE]
[CHARACTERS: Ren, Kira, Bradley, Liora, Dante, Shadow]
[DURATION: 3:24]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of EXT. FINAL RIDGE
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v2-Act2-Ch09-s11",
    volumeId: 2,
    chapter: "Act2_Ch09",
    sceneNumber: 11,
    title: "Mist-Field Outskirts",
    characters: ["Ren", "Kira", "Bradley", "Liora", "Shadow"],
    durationStr: "3:24",
    durationSeconds: 204,
    location: "EXT. MIST-FIELD OUTSKIRTS",
    priorityTier: 3 as const,
    promptTemplate: `[SCENE: Mist-Field Outskirts]
[VOLUME: 2]
[CHAPTER: Act2_Ch09]
[LOCATION: EXT. MIST-FIELD OUTSKIRTS]
[CHARACTERS: Ren, Kira, Bradley, Liora, Shadow]
[DURATION: 3:24]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of EXT. MIST-FIELD OUTSKIRTS
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v3-Act3-Ch05-s1",
    volumeId: 3,
    chapter: "Act3_Ch05",
    sceneNumber: 1,
    title: "Monica vs. Kael",
    characters: ["Ren", "Kira", "Monica", "Kael", "Fasa"],
    durationStr: "3:21",
    durationSeconds: 201,
    location: "EXT. RITE OF DOMINION ARENA",
    priorityTier: 3 as const,
    promptTemplate: `[SCENE: Monica vs. Kael]
[VOLUME: 3]
[CHAPTER: Act3_Ch05]
[LOCATION: EXT. RITE OF DOMINION ARENA]
[CHARACTERS: Ren, Kira, Monica, Kael, Fasa]
[DURATION: 3:21]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of EXT. RITE OF DOMINION ARENA
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v2-Act2-Ch03-s10",
    volumeId: 2,
    chapter: "Act2_Ch03",
    sceneNumber: 10,
    title: "Deep War Room - Mission Briefing",
    characters: ["Ren", "Bradley", "Dante", "Solana", "Queen", "Shadow"],
    durationStr: "3:20",
    durationSeconds: 200,
    location: "INT. SHADOW GUILD",
    priorityTier: 3 as const,
    promptTemplate: `[SCENE: Deep War Room - Mission Briefing]
[VOLUME: 2]
[CHAPTER: Act2_Ch03]
[LOCATION: INT. SHADOW GUILD]
[CHARACTERS: Ren, Bradley, Dante, Solana, Queen, Shadow]
[DURATION: 3:20]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of INT. SHADOW GUILD
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v2-Act2-Ch03-s2",
    volumeId: 2,
    chapter: "Act2_Ch03",
    sceneNumber: 2,
    title: "The Armory's Whisper",
    characters: ["Ren", "Monica", "Dante", "Shadow"],
    durationStr: "3:13",
    durationSeconds: 193,
    location: "INT. SHADOW GUILD ARMORY — LAT",
    priorityTier: 3 as const,
    promptTemplate: `[SCENE: The Armory's Whisper]
[VOLUME: 2]
[CHAPTER: Act2_Ch03]
[LOCATION: INT. SHADOW GUILD ARMORY — LAT]
[CHARACTERS: Ren, Monica, Dante, Shadow]
[DURATION: 3:13]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of INT. SHADOW GUILD ARMORY — LAT
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v3-Act3-Ch09-s4",
    volumeId: 3,
    chapter: "Act3_Ch09",
    sceneNumber: 4,
    title: "No More Running (Part 3: Demon Crown Stirring)",
    characters: ["Ren", "Monica", "Dante", "Queen", "Shadow"],
    durationStr: "3:11",
    durationSeconds: 191,
    location: "EXT. GLYPH RUINS",
    priorityTier: 3 as const,
    promptTemplate: `[SCENE: No More Running (Part 3: Demon Crown Stirring)]
[VOLUME: 3]
[CHAPTER: Act3_Ch09]
[LOCATION: EXT. GLYPH RUINS]
[CHARACTERS: Ren, Monica, Dante, Queen, Shadow]
[DURATION: 3:11]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of EXT. GLYPH RUINS
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v1-Act1-Ch01-s6",
    volumeId: 1,
    chapter: "Act1_Ch01",
    sceneNumber: 6,
    title: "Betrayal",
    characters: ["Ren", "Monica"],
    durationStr: "3:09",
    durationSeconds: 189,
    location: "Unknown",
    priorityTier: 3 as const,
    promptTemplate: `[SCENE: Betrayal]
[VOLUME: 1]
[CHAPTER: Act1_Ch01]
[LOCATION: Unknown]
[CHARACTERS: Ren, Monica]
[DURATION: 3:09]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of Unknown
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v2-Act2-Ch03-s6",
    volumeId: 2,
    chapter: "Act2_Ch03",
    sceneNumber: 6,
    title: "Common Hall Breakfast",
    characters: ["Ren", "Kira", "Bradley", "Dante", "Shadow"],
    durationStr: "2:56",
    durationSeconds: 176,
    location: "INT. SHADOW GUILD COMMON HALL",
    priorityTier: 4 as const,
    promptTemplate: `[SCENE: Common Hall Breakfast]
[VOLUME: 2]
[CHAPTER: Act2_Ch03]
[LOCATION: INT. SHADOW GUILD COMMON HALL]
[CHARACTERS: Ren, Kira, Bradley, Dante, Shadow]
[DURATION: 2:56]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of INT. SHADOW GUILD COMMON HALL
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v3-Act3-Ch05-s2",
    volumeId: 3,
    chapter: "Act3_Ch05",
    sceneNumber: 2,
    title: "Bradley’s Tech-Magic Duel",
    characters: ["Ren", "Monica", "Bradley", "Liora", "Fasa"],
    durationStr: "2:44",
    durationSeconds: 164,
    location: "EXT. RITE OF DOMINION ARENA",
    priorityTier: 4 as const,
    promptTemplate: `[SCENE: Bradley’s Tech-Magic Duel]
[VOLUME: 3]
[CHAPTER: Act3_Ch05]
[LOCATION: EXT. RITE OF DOMINION ARENA]
[CHARACTERS: Ren, Monica, Bradley, Liora, Fasa]
[DURATION: 2:44]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of EXT. RITE OF DOMINION ARENA
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v2-Act2-Ch03-s7",
    volumeId: 2,
    chapter: "Act2_Ch03",
    sceneNumber: 7,
    title: "Blades Between Equals",
    characters: ["Ren", "Dante", "Shadow"],
    durationStr: "2:37",
    durationSeconds: 157,
    location: "INT. SHADOW GUILD COMBAT PIT —",
    priorityTier: 4 as const,
    promptTemplate: `[SCENE: Blades Between Equals]
[VOLUME: 2]
[CHAPTER: Act2_Ch03]
[LOCATION: INT. SHADOW GUILD COMBAT PIT —]
[CHARACTERS: Ren, Dante, Shadow]
[DURATION: 2:37]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of INT. SHADOW GUILD COMBAT PIT —
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v2-Act2-Ch05-s9",
    volumeId: 2,
    chapter: "Act2_Ch05",
    sceneNumber: 9,
    title: "Ajax Battle and Escape",
    characters: ["Ren", "Bradley", "Dante"],
    durationStr: "2:37",
    durationSeconds: 157,
    location: "INT. SIGMA-13",
    priorityTier: 4 as const,
    promptTemplate: `[SCENE: Ajax Battle and Escape]
[VOLUME: 2]
[CHAPTER: Act2_Ch05]
[LOCATION: INT. SIGMA-13]
[CHARACTERS: Ren, Bradley, Dante]
[DURATION: 2:37]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of INT. SIGMA-13
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v3-Act3-Ch09-s4",
    volumeId: 3,
    chapter: "Act3_Ch09",
    sceneNumber: 4,
    title: "No More Running (Part 1)",
    characters: ["Ren", "Monica", "Dante", "Shadow"],
    durationStr: "2:29",
    durationSeconds: 149,
    location: "EXT. GLYPH GATE RUINS",
    priorityTier: 4 as const,
    promptTemplate: `[SCENE: No More Running (Part 1)]
[VOLUME: 3]
[CHAPTER: Act3_Ch09]
[LOCATION: EXT. GLYPH GATE RUINS]
[CHARACTERS: Ren, Monica, Dante, Shadow]
[DURATION: 2:29]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of EXT. GLYPH GATE RUINS
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v2-Act2-Ch06-s3",
    volumeId: 2,
    chapter: "Act2_Ch06",
    sceneNumber: 3,
    title: "Outer Ridge - Battle Escalates",
    characters: ["Ren", "Kira", "Bradley", "Shadow"],
    durationStr: "2:20",
    durationSeconds: 140,
    location: "EXT. OUTER RIDGE",
    priorityTier: 4 as const,
    promptTemplate: `[SCENE: Outer Ridge - Battle Escalates]
[VOLUME: 2]
[CHAPTER: Act2_Ch06]
[LOCATION: EXT. OUTER RIDGE]
[CHARACTERS: Ren, Kira, Bradley, Shadow]
[DURATION: 2:20]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of EXT. OUTER RIDGE
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v2-Act2-Ch08-s6",
    volumeId: 2,
    chapter: "Act2_Ch08",
    sceneNumber: 6,
    title: "Solana's Last Stand",
    characters: ["Dante", "Solana", "Shadow"],
    durationStr: "2:16",
    durationSeconds: 136,
    location: "INT. SHADOW GUILD COURTYARD",
    priorityTier: 4 as const,
    promptTemplate: `[SCENE: Solana's Last Stand]
[VOLUME: 2]
[CHAPTER: Act2_Ch08]
[LOCATION: INT. SHADOW GUILD COURTYARD]
[CHARACTERS: Dante, Solana, Shadow]
[DURATION: 2:16]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of INT. SHADOW GUILD COURTYARD
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v2-Act2-Ch08-s1",
    volumeId: 2,
    chapter: "Act2_Ch08",
    sceneNumber: 1,
    title: "Guild Courtyard - Pre-Battle",
    characters: ["Ren", "Kira", "Bradley", "Liora", "Solana", "Shadow"],
    durationStr: "1:53",
    durationSeconds: 113,
    location: "INT. SHADOW GUILD COURTYARD",
    priorityTier: 4 as const,
    promptTemplate: `[SCENE: Guild Courtyard - Pre-Battle]
[VOLUME: 2]
[CHAPTER: Act2_Ch08]
[LOCATION: INT. SHADOW GUILD COURTYARD]
[CHARACTERS: Ren, Kira, Bradley, Liora, Solana, Shadow]
[DURATION: 1:53]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of INT. SHADOW GUILD COURTYARD
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v2-Act2-Ch09-s10",
    volumeId: 2,
    chapter: "Act2_Ch09",
    sceneNumber: 10,
    title: "Ridge Pass Ambush",
    characters: ["Ren", "Kira", "Bradley", "Liora"],
    durationStr: "1:51",
    durationSeconds: 111,
    location: "EXT. RIDGE PASS",
    priorityTier: 4 as const,
    promptTemplate: `[SCENE: Ridge Pass Ambush]
[VOLUME: 2]
[CHAPTER: Act2_Ch09]
[LOCATION: EXT. RIDGE PASS]
[CHARACTERS: Ren, Kira, Bradley, Liora]
[DURATION: 1:51]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of EXT. RIDGE PASS
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v2-Act2-Ch08-s5",
    volumeId: 2,
    chapter: "Act2_Ch08",
    sceneNumber: 5,
    title: "Courtyard Center Fight",
    characters: ["Dante", "Solana", "Queen", "Shadow"],
    durationStr: "1:47",
    durationSeconds: 107,
    location: "INT. COURTYARD CENTER",
    priorityTier: 4 as const,
    promptTemplate: `[SCENE: Courtyard Center Fight]
[VOLUME: 2]
[CHAPTER: Act2_Ch08]
[LOCATION: INT. COURTYARD CENTER]
[CHARACTERS: Dante, Solana, Queen, Shadow]
[DURATION: 1:47]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of INT. COURTYARD CENTER
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v2-Act2-Ch08-s9",
    volumeId: 2,
    chapter: "Act2_Ch08",
    sceneNumber: 9,
    title: "Ren's Rage",
    characters: ["Ren", "Dante", "Queen"],
    durationStr: "1:26",
    durationSeconds: 86,
    location: "INT. BATTLEFIELD",
    priorityTier: 4 as const,
    promptTemplate: `[SCENE: Ren's Rage]
[VOLUME: 2]
[CHAPTER: Act2_Ch08]
[LOCATION: INT. BATTLEFIELD]
[CHARACTERS: Ren, Dante, Queen]
[DURATION: 1:26]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of INT. BATTLEFIELD
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v2-Act2-Ch08-s4",
    volumeId: 2,
    chapter: "Act2_Ch08",
    sceneNumber: 4,
    title: "Battle Begins",
    characters: ["Liora", "Queen", "Shadow"],
    durationStr: "1:19",
    durationSeconds: 79,
    location: "INT. SHADOW GUILD COURTYARD",
    priorityTier: 4 as const,
    promptTemplate: `[SCENE: Battle Begins]
[VOLUME: 2]
[CHAPTER: Act2_Ch08]
[LOCATION: INT. SHADOW GUILD COURTYARD]
[CHARACTERS: Liora, Queen, Shadow]
[DURATION: 1:19]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of INT. SHADOW GUILD COURTYARD
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v3-Act3-Ch01-s3",
    volumeId: 3,
    chapter: "Act3_Ch01",
    sceneNumber: 3,
    title: "Battle Sequence - Gladiator vs Ice Blade",
    characters: ["Kira", "Monica"],
    durationStr: "1:02",
    durationSeconds: 62,
    location: "Unknown",
    priorityTier: 4 as const,
    promptTemplate: `[SCENE: Battle Sequence - Gladiator vs Ice Blade]
[VOLUME: 3]
[CHAPTER: Act3_Ch01]
[LOCATION: Unknown]
[CHARACTERS: Kira, Monica]
[DURATION: 1:02]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of Unknown
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  },
  {
    id: "fight-v3-Act3-Ch03-s6",
    volumeId: 3,
    chapter: "Act3_Ch03",
    sceneNumber: 6,
    title: "Combat",
    characters: ["Ren", "Kira", "Monica", "Bradley"],
    durationStr: "0:35",
    durationSeconds: 35,
    location: "INT. SHRINE",
    priorityTier: 4 as const,
    promptTemplate: `[SCENE: Combat]
[VOLUME: 3]
[CHAPTER: Act3_Ch03]
[LOCATION: INT. SHRINE]
[CHARACTERS: Ren, Kira, Monica, Bradley]
[DURATION: 0:35]

VISUAL DESCRIPTION:
{Describe the key visual moment from this scene}

CAMERA:
- Opening: Wide establishing shot of INT. SHRINE
- Action: Dynamic tracking shot following combat
- Close-up: Character reaction/transformation moment

STYLE NOTES:
- Anime aesthetic, dark fantasy
- Ufotable animation style reference
- High contrast lighting with elemental effects
- Dynamic motion blur on combat impacts

SORA PROMPT DRAFT:
[SHOT TYPE] [CHARACTER] [ACTION] in [ENVIRONMENT]. [LIGHTING]. [CAMERA MOVEMENT]. Anime-inspired, dark fantasy aesthetic, Ufotable animation style.`
  }
];

// Helper functions
export function getFightScenesByVolume(volumeId: number): FightScene[] {
  return fightScenes.filter(scene => scene.volumeId === volumeId);
}

export function getFightScenesByTier(tier: 1 | 2 | 3 | 4): FightScene[] {
  return fightScenes.filter(scene => scene.priorityTier === tier);
}

export function getFightScenesByCharacter(character: string): FightScene[] {
  const lowerChar = character.toLowerCase();
  return fightScenes.filter(scene =>
    scene.characters.some(c => c.toLowerCase().includes(lowerChar))
  );
}

export function getTopFightScenes(count: number = 10): FightScene[] {
  return fightScenes.slice(0, count);
}

export function getTotalFightDuration(): { minutes: number; formatted: string } {
  const totalSeconds = fightScenes.reduce((sum, s) => sum + s.durationSeconds, 0);
  const minutes = Math.floor(totalSeconds / 60);
  return {
    minutes,
    formatted: `${minutes} minutes`
  };
}
